name: Daily Scheduled Commit

on:
  schedule:
    - cron: '43 4 * * *'  # Runs every day at 04:43 UTC

jobs:
  commit-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create Commit - 23f3001787@ds.study.iitm.ac.in
        run: |
          echo "Daily commit run at $(date)" >> commit.txt
          git config user.name "github-actions"
          git config user.email "23f3001787@ds.study.iitm.ac.in"
          git add commit.txt
          git commit -m "Daily commit $(date)" || echo "No changes to commit"

      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
